USE databruh_db;
CREATE INDEX idx_driver_fullname ON driver(FullName);
CREATE INDEX idx_vda_vehicle_enddate ON vehicle_driver_assignment(VehicleID, EndDate);
CREATE INDEX idx_vda_driver_enddate ON vehicle_driver_assignment(DriverID, EndDate);
CREATE INDEX idx_driver_cert_owned_expiry ON driver_certification_owned(ExpiryDate);
CREATE INDEX idx_monthly_score_log_driver_year_month ON monthly_score_log(DriverID, Year, Month);
CREATE INDEX idx_behaviour_event_driver_timestamp ON behaviour_event(DriverID, Timestamp);
CREATE INDEX idx_alert_status_timestamp ON alert(Status, AlertTimestamp);
CREATE INDEX idx_maintenance_job_status ON maintenance_job(Status);
CREATE INDEX idx_maintenance_job_startdate ON maintenance_job(StartDate);
CREATE INDEX idx_mechanic_worker_fullname ON mechanic_worker(FullName);
CREATE INDEX idx_part_partname ON part(PartName);
CREATE UNIQUE INDEX idx_supplier_product_list_part_partner ON supplier_product_list(PartID, PartnerID);
CREATE INDEX idx_coaching_log_driver_outcome ON coaching_log(DriverID, Outcome);